---
- name: Install MySQL Community repo (EL YUM)
  yum: name="{{ mysql_repo_url }}" state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora' and ansible_pkg_mgr == 'yum'

- name: Install MySQL Community repo (Fedora DNF)
  dnf: name="{{ mysql_repo_url }}" state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora' and ansible_pkg_mgr == 'dnf'

- name: Import MySQL Community GPG key (EL/Fedora)
  rpm_key:
    key: "{{ mysql_repo_gpg_key_url }}"
    state: present
  when: ansible_os_family == 'RedHat'
