---
- name: Install repository repo
  package:
    deb: "{{ mysql_repo_deb_url }}"
    state: present

- name: Import repository GPG key
  apt_key:
    id: "{{ mysql_repo_key_id }}"
    url: "{{ mysql_repo_key_url }}"
    state: present
